In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('football-events\ginf.csv')
dff = pd.read_csv('football-events\events.csv')

In [24]:
df.count()

id_odsp      10112
link_odsp    10112
adv_stats    10112
date         10112
league       10112
season       10112
country      10112
ht           10112
at           10112
fthg         10112
ftag         10112
odd_h        10112
odd_d        10112
odd_a        10112
odd_over       977
odd_under      977
odd_bts        977
odd_bts_n      977
dtype: int64

In [25]:
dff.count()

id_odsp          941009
id_event         941009
sort_order       941009
time             941009
text             941009
event_type       941009
event_type2      214293
side             941009
event_team       941009
opponent         941009
player           880009
player2          291310
player_in         51715
player_out        51738
shot_place       227459
shot_outcome     228498
is_goal          941009
location         467067
bodypart         229185
assist_method    941009
situation        229137
fast_break       941009
dtype: int64

In [33]:
#Tipo um inner Join entre od dataframes
//pd.merge(df, dff, on=['id_odsp', 'id_odsp'])

SyntaxError: invalid syntax (<ipython-input-33-030d72889fed>, line 2)

In [36]:
djj = pd.merge(df, dff, on=['id_odsp','id_odsp'])

#Pegando os registros aos quais foram cartões amarelos, segundo amarelos ou vermelhos
##dfcards = dj.loc[(dj['event_type'] == 4) | (dj['event_type'] == 5) | (dj['event_type'] == 6)]

In [38]:
dfcards = djj[(djj['event_type'] == 6)]

##dfcards.groupby(['league', 'date', 'id_odsp']).head()

##dj.loc[(dj['league'] == 'D1') & (dj['date'].find('2011') != -1].count()

In [37]:
djj.head()

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
2,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0

In [39]:
dfcards.head()

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
1297,WQGN5NXn/,/soccer/france/ligue-1-2011-2012/nancy-lille-W...,True,2011-08-06,F1,2012,france,AS Nancy Lorraine,Lille,1,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
5236,tl4D8Ggo/,/soccer/france/ligue-1-2011-2012/dijon-lorient...,True,2011-08-20,F1,2012,france,Dijon FCO,Lorient,2,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
5708,fydAFnSc/,/soccer/france/ligue-1-2011-2012/nancy-sochaux...,True,2011-08-21,F1,2012,france,AS Nancy Lorraine,Sochaux,1,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
6378,0QSBhGQ1/,/soccer/france/ligue-1-2011-2012/lyon-montpell...,True,2011-08-27,F1,2012,france,Lyon,Montpellier,2,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
6685,CtEdUSdJ/,/soccer/spain/primera-division-2011-2012/gijon...,True,2011-08-27,SP1,2012,spain,Sporting Gijon,Real Sociedad,1,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [31]:
df.h

AttributeError: 'DataFrame' object has no attribute 'h'